// Platform-level publish system for cross-region sharing
import { t } from './i18n';

export type PublishRegion = 'KR' | 'EN' | 'CN';

export interface RegionTemplate {
  titlePattern: string;
  descriptionPattern: string;
  hashtags: string[];
  platformSpecific?: {
    youtube?: { titleSuffix?: string; descriptionPrefix?: string };
    tiktok?: { titleSuffix?: string; hashtagLimit?: number };
    instagram?: { titleSuffix?: string; hashtagLimit?: number };
  };
}

export interface PublishMetadata {
  title: string;
  description: string;
  hashtags: string[];
  region: PublishRegion;
  videoUrl: string;
  duration?: string;
  aspectRatio?: string;
}

// Region-specific templates and patterns
const REGION_TEMPLATES: Record<PublishRegion, RegionTemplate> = {
  KR: {
    titlePattern: '{title} | AI 생성 영상',
    descriptionPattern: 'AI로 생성된 창의적인 영상입니다.\n\n원본 프롬프트: {prompt}\n\n#AI영상 #창작콘텐츠',
    hashtags: [
      '#AI영상', '#인공지능', '#창작콘텐츠', '#디지털아트',
      '#영상제작', '#크리에이티브', '#테크놀로지', '#혁신',
      '#미디어아트', '#자동생성', '#콘텐츠제작', '#영상편집',
      '#디지털크리에이터', '#AI아트', '#영상콘텐츠', '#창의적사고',
      '#기술혁신', '#미래기술', '#스마트콘텐츠', '#디지털미디어'
    ],
    platformSpecific: {
      youtube: { titleSuffix: ' - AI Generated', descriptionPrefix: '🤖 AI로 제작된 영상입니다\n\n' },
      tiktok: { titleSuffix: ' #AI영상', hashtagLimit: 10 },
      instagram: { titleSuffix: ' 🤖', hashtagLimit: 15 }
    }
  },
  EN: {
    titlePattern: '{title} | AI Generated Video',
    descriptionPattern: 'Creative video generated using AI technology.\n\nOriginal prompt: {prompt}\n\n#AIVideo #CreativeContent',
    hashtags: [
      '#AIVideo', '#ArtificialIntelligence', '#CreativeContent', '#DigitalArt',
      '#VideoProduction', '#Creative', '#Technology', '#Innovation',
      '#MediaArt', '#AutoGenerated', '#ContentCreation', '#VideoEditing',
      '#DigitalCreator', '#AIArt', '#VideoContent', '#CreativeThinking',
      '#TechInnovation', '#FutureTech', '#SmartContent', '#DigitalMedia'
    ],
    platformSpecific: {
      youtube: { titleSuffix: ' - AI Generated', descriptionPrefix: '🤖 AI-generated video content\n\n' },
      tiktok: { titleSuffix: ' #AIVideo', hashtagLimit: 10 },
      instagram: { titleSuffix: ' 🤖', hashtagLimit: 15 }
    }
  },
  CN: {
    titlePattern: '{title} | AI生成视频',
    descriptionPattern: '使用AI技术生成的创意视频。\n\n原始提示: {prompt}\n\n#AI视频 #创意内容',
    hashtags: [
      '#AI视频', '#人工智能', '#创意内容', '#数字艺术',
      '#视频制作', '#创意', '#科技', '#创新',
      '#媒体艺术', '#自动生成', '#内容创作', '#视频编辑',
      '#数字创作者', '#AI艺术', '#视频内容', '#创意思维',
      '#技术创新', '#未来科技', '#智能内容', '#数字媒体'
    ],
    platformSpecific: {
      youtube: { titleSuffix: ' - AI生成', descriptionPrefix: '🤖 AI生成的视频内容\n\n' },
      tiktok: { titleSuffix: ' #AI视频', hashtagLimit: 10 },
      instagram: { titleSuffix: ' 🤖', hashtagLimit: 15 }
    }
  }
};

export class PublishManager {
  // Generate metadata for a specific region
  static generateMetadata(
    videoTitle: string,
    videoPrompt: string,
    videoUrl: string,
    region: PublishRegion,
    platform?: 'youtube' | 'tiktok' | 'instagram'
  ): PublishMetadata {
    const template = REGION_TEMPLATES[region];
    
    // Generate title with pattern
    let title = template.titlePattern
      .replace('{title}', videoTitle)
      .replace('{prompt}', videoPrompt);
    
    // Apply platform-specific title modifications
    if (platform && template.platformSpecific?.[platform]?.titleSuffix) {
      title += template.platformSpecific[platform].titleSuffix;
    }
    
    // Generate description with pattern
    let description = template.descriptionPattern
      .replace('{title}', videoTitle)
      .replace('{prompt}', videoPrompt);
    
    // Apply platform-specific description modifications
    if (platform && template.platformSpecific?.[platform]?.descriptionPrefix) {
      description = template.platformSpecific[platform].descriptionPrefix + description;
    }
    
    // Select hashtags based on platform limits
    let hashtags = [...template.hashtags];
    if (platform && template.platformSpecific?.[platform]?.hashtagLimit) {
      const limit = template.platformSpecific[platform].hashtagLimit!;
      hashtags = hashtags.slice(0, limit);
    }
    
    return {
      title: title.trim(),
      description: description.trim(),
      hashtags,
      region,
      videoUrl,
    };
  }
  
  // Get region display name
  static getRegionDisplayName(region: PublishRegion): string {
    const names = {
      KR: '한국 (Korean)',
      EN: 'English (Global)',
      CN: '中文 (Chinese)'
    };
    return names[region];
  }
  
  // Get available regions
  static getAvailableRegions(): PublishRegion[] {
    return ['KR', 'EN', 'CN'];
  }
  
  // Validate video URL for publishing
  static async validateVideoUrl(videoUrl: string): Promise<{ valid: boolean; error?: string }> {
    try {
      const response = await fetch(videoUrl, { method: 'HEAD' });
      if (!response.ok) {
        return { 
          valid: false, 
          error: `Video not accessible (${response.status})` 
        };
      }
      return { valid: true };
    } catch (error: any) {
      return { 
        valid: false, 
        error: error.message || 'Network error accessing video' 
      };
    }
  }
  
  // Copy text to clipboard
  static async copyToClipboard(text: string): Promise<boolean> {
    try {
      await navigator.clipboard.writeText(text);
      return true;
    } catch (error) {
      console.error('Failed to copy to clipboard:', error);
      return false;
    }
  }
  
  // Generate shareable link (if allowed by capabilities)
  static generateShareableLink(videoId: string, region?: PublishRegion): string {
    const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
    let shareUrl = `${baseUrl}/dashboard/videos/${videoId}`;
    
    if (region) {
      shareUrl += `?region=${region}`;
    }
    
    return shareUrl;
  }
  
  // Download video file
  static async downloadVideo(
    videoUrl: string, 
    filename: string,
    onProgress?: (progress: number) => void
  ): Promise<{ success: boolean; error?: string }> {
    try {
      const response = await fetch(videoUrl);
      
      if (!response.ok) {
        return { 
          success: false, 
          error: `Download failed: ${response.status} ${response.statusText}` 
        };
      }
      
      const contentLength = response.headers.get('content-length');
      const total = contentLength ? parseInt(contentLength, 10) : 0;
      let loaded = 0;
      
      const reader = response.body?.getReader();
      if (!reader) {
        return { success: false, error: 'Unable to read video stream' };
      }
      
      const chunks: Uint8Array[] = [];
      
      while (true) {
        const { done, value } = await reader.read();
        
        if (done) break;
        
        chunks.push(value);
        loaded += value.length;
        
        if (onProgress && total > 0) {
          onProgress((loaded / total) * 100);
        }
      }
      
      // Create blob and download
      const blob = new Blob(chunks, { type: 'video/mp4' });
      const url = window.URL.createObjectURL(blob);
      
      const a = document.createElement('a');
      a.style.display = 'none';
      a.href = url;
      a.download = filename;
      
      document.body.appendChild(a);
      a.click();
      
      // Cleanup
      setTimeout(() => {
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
      }, 100);
      
      return { success: true };
    } catch (error: any) {
      return { 
        success: false, 
        error: error.message || 'Download failed' 
      };
    }
  }
}